/**
 * Icon mapping — Material Symbols (mockup parity) → Lucide.
 *
 * Cardinal rule (AGENTS.md #3): NEVER use emojis or Material Symbols as UI icons.
 * Lucide-only via this mapping. New icons must be added here.
 */

import {
  AlertTriangle,
  ArrowRight,
  BadgeCheck,
  Banknote,
  Camera,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CirclePlus,
  CircleUser,
  ClockAlert,
  Copy,
  Download,
  Droplets,
  Eye,
  FileText,
  Flag,
  HandHeart,
  Handshake,
  Heart,
  HeartPulse,
  History,
  LayoutDashboard,
  Leaf,
  ListFilter,
  ListChecks,
  MapPin,
  NotebookPen,
  Package,
  Pencil,
  PiggyBank,
  Plus,
  Receipt,
  ReceiptText,
  Search,
  Settings,
  ShoppingCart,
  Stethoscope,
  TreePine,
  TrendingUp,
  Trash2,
  Truck,
  UserX,
  Users,
  Users2,
  type LucideIcon,
} from 'lucide-react';

export const iconMap = {
  // mockup name (Material Symbols Outlined) → Lucide component
  account_circle: CircleUser,
  add: Plus,
  add_circle: CirclePlus,
  arrow_forward: ArrowRight,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  content_copy: Copy,
  dashboard: LayoutDashboard,
  delete: Trash2,
  diversity_3: Users,
  download: Download,
  eco: Leaf,
  edit: Pencil,
  edit_note: NotebookPen,
  expand_more: ChevronDown,
  favorite: Heart,
  filter_list: ListFilter,
  flag: Flag,
  forest: TreePine,
  groups: Users2,
  handshake: Handshake,
  hand_heart: HandHeart,
  history: History,
  inventory_2: Package,
  list_checks: ListChecks,
  local_shipping: Truck,
  location_on: MapPin,
  medical_services: Stethoscope,
  monitor_heart: HeartPulse,
  payments: Banknote,
  pending_actions: ClockAlert,
  person_off: UserX,
  photo_camera: Camera,
  picture_as_pdf: FileText,
  priority_high: AlertTriangle,
  receipt: Receipt,
  receipt_long: ReceiptText,
  savings: PiggyBank,
  search: Search,
  settings: Settings,
  shopping_cart: ShoppingCart,
  trending_up: TrendingUp,
  verified: BadgeCheck,
  visibility: Eye,
  volunteer_activism: HandHeart,
  water_drop: Droplets,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export function getIcon(name: IconName): LucideIcon {
  return iconMap[name];
}
